db/install.xml, db/upgrade.php, lang/en/local_helpdesk.php, locallib.php, mailtemplatelib.php, view.php
=> add changes view, lang, add new features in mail, db and locallib 

db/install.xml, db/upgrade.php, index.php, lang/en/local_helpdesk.php, version.php, view.php
=> refactor delete unused code, add xml db table helpdesk

forms/report_issue_form.php, lang/en/local_helpdesk.php, locallib.php, menus.php, report_issue.php, version.php
=> create report form

db/install.xml, db/upgrade.php, forms/report_issue_form.php, lang/en/local_helpdesk.php, locallib.php, report_issue.php, version.php, view.php, views/view_issues.php, views/view_tickets_list.php
=> create table for all tickets, translate lang strings, add report order to database

locallib.php, views/view_issues.php
=> set attributes, status code, update view issues table

db/access.php, lang/en/local_helpdesk.php, locallib.php, view.php, views/view_assigned_issues.php, views/view_issues.php
=> add new view with user tickets into table lise

db/access.php, lang/en/local_helpdesk.php, menus.php, renderer.php, version.php, views/viewassignedtickets.php
=> feat access and string lang, delete search tab, fix assingned view

db/access.php, lang/en/local_helpdesk.php, menus.php, renderer.php, styles.css, version.php, view.php, views/viewassignedtickets.php, views/viewtickets.php
=> refactor the table of assigned issues tab, add styles, redirect, cleanup code

lang/en/local_helpdesk.php, version.php, views/viewassignedtickets.php, views/viewtickets.php
=> display table with all issues

db/install.xml, db/upgrade.php, version.php, view.php, views/viewassignedtickets.php, views/viewcontroller.php
=> working on changing status of issue state 

locallib.php, menus.php, renderer.php, views/viewassignedtickets.php, views/viewcontroller.php, views/viewtickets.php
=> add issue counter, add func to update the issue priority

lang/en/local_helpdesk.php, view.php, views/viewassignedtickets.php, views/viewcontroller.php
=> add resolve view tab, refactor code

locallib.php, renderer.php, version.php, views/viewanissue.php
=> render table and rows of the issue view screen

renderer.php, views/viewanissue.php
=> working on view an issues table

db/upgrade.php, forms/reportissue_form.php, locallib.php, menus.php, renderer.php, reportissue.php, view.php, views/viewanissue.php, views/viewcontroller.php, views/viewtickets.php
=> project: refactor code use phpstorm code inspector

lang/en/local_helpdesk.php, renderer.php, styles.css, views/viewanissue.php, views/viewtickets.php
=> create table and rows of view an issue

lang/en/local_helpdesk.php, locallib.php, menus.php, renderer.php, version.php, view.php, views/viewanissue.php, views/viewcontroller.php
=> fix the resolved tab, create the data for history ui 

db/install.xml, db/upgrade.php, version.php, views/viewanissue.php
=> craete the the helpdesk_issueownership table and history button to viewanissue.php

js/helpdeskview.js, lang/en/local_helpdesk.php, renderer.php, version.php, view.php, views/viewanissue.php
=> display the table history of issues, add script to toggle state of it

db/install.xml, db/upgrade.php, js/helpdeskview.js, locallib.php, renderer.php, reportissue.php, styles.css, version.php, view.php, views/viewanissue.php
=> added the helpdesk_issuecomment, refactor the code lines and the logic of functions

db/access.php, js/helpdeskview.js, lang/en/local_helpdesk.php, renderer.php, version.php, views/viewcontroller.php, views/viewtickets.php
=> created the toggle panel with history operations into the view an issue

addcomment.php, forms/addcomment_form.php, forms/reportissue_form.php, lang/en/local_helpdesk.php, menus.php, reportissue.php, version.php, view.php, views/viewanissue.php, views/viewassignedtickets.php
=> added the addcomment view + the moodle addcomment_form class

addcomment.php, forms/addcomment_form.php, lang/en/local_helpdesk.php, version.php, view.php, views/viewanissue.php
=> added the comment view, setup the new comment data to database

addcomment.php, forms/addcomment_form.php, forms/reportissue_form.php, renderer.php, version.php, view.php, views/viewanissue.php, views/viewcontroller.php
=> Display the comments to viewanissue screen

lang/en/local_helpdesk.php, locallib.php, version.php, view.php, views/editanissue.php
=> added the editanissue.php screen

lang/en/local_helpdesk.php, locallib.php, version.php, views/editanissue.php
=> added the rows of table editanissue screen

locallib.php, styles.css, version.php, views/editanissue.php
=> added content settings for editor in the editanissue screen

addcomment.php, lang/en/local_helpdesk.php, locallib.php, version.php, views/editanissue.php, views/viewcontroller.php
=> Finished creating the editor form to editanissue screen

views/viewassignedtickets.php, views/viewcontroller.php
=> fix redirect with resolve tab when change the status issue from view screen tab

locallib.php, views/editanissue.php
=> chore: refactor and fix minor bugs

locallib.php, views/editanissue.php
=> added the selected list categories of editanissue screen

locallib.php, views/viewcontroller.php
=> added handler the updateanissue action in viewcontroller.php

locallib.php, version.php, views/viewcontroller.php, views/viewtickets.php
=> fixed the work with issues priority of the button actions

locallib.php, views/viewassignedtickets.php, views/viewcontroller.php, views/viewtickets.php
=> added able to assign managers for the tickets

addcomment.php, lang/en/local_helpdesk.php, menus.php, renderer.php, version.php, view.php, views/addcategory.php, views/addmanagers.php, views/assignmanagers.php, views/categories.viewcontroller.php, views/viewcontroller.php
=> added the controller and view for the screen categories

forms/addcategory_form.php, view.php, views/addcategory.php, views/assignmanagers.php, views/viewassignedtickets.php, views/viewcontroller.php, views/viewtickets.php
=> added the screen tabs for manage the user categories

locallib.php, views/assignmanagers.php
=> Get the helpdesk categories and actions for doing operations with category

forms/addcategory_form.php, lang/en/local_helpdesk.php, locallib.php, renderer.php, version.php, view.php, views/addcategory.php, views/assignmanagers.php
=> display the assign managers form

lang/en/local_helpdesk.php, version.php, views/assignmanagers.php
=> added the selector form with options

lang/en/local_helpdesk.php, locallib.php, version.php, views/assignmanagers.php
=> added the select html elements to categoryeditform

lang/en/local_helpdesk.php, version.php, views/assignmanagers.php
=> edit places of the html elements, delete unused the html elements

js/helpdeskview.js, lang/en/local_helpdesk.php, version.php, views/assignmanagers.php
=> added the script to manage the members categories 

js/helpdeskview.js, locallib.php, views/assignmanagers.php
=> added optional params and styled the submit buttons in the assignmanagers file

addcategory.php, categories/addmanagers.php, categories/managecategories.php, categories/viewcontroller.php, db/upgrade.php, forms/addcategory_form.php, menus.php, renderer.php, version.php, view.php
=> added helpdesk_categories table to the database

categories/managecategories.php, js/helpdeskview.js, locallib.php, view.php, views/editanissue.php
=> fixed request to the managecategories screen, replaced the incorrect js_init_code function

categories/managecategories.php, categories/viewcontroller.php, db/install.xml, db/upgrade.php, js/helpdeskview.js, locallib.php, version.php
=> added more features to js scripts and the new table to database

categories/managecategories.php, categories/viewcontroller.php, js/helpdeskview.js, locallib.php, members.php
=> added new action - showaddmembersform and the new page for adding a new users to category 

lang/en/local_helpdesk.php, members.php, version.php
=> added the page table with the category and the members columns

locallib.php, members.php
=> added the function to get the all members from database

js/helpdeskview.js, locallib.php, members.php
=> displayed members in column of the table

js/helpdeskview.js, members.php, version.php, views/viewtickets.php
=> added the new script for the members view

js/helpdeskview.js, searchmembers.php
=> added the search members function using the input field

js/helpdeskview.js, members.php, searchmembers.php
=> deleted the old ajax method, using fetch to getting results from the server

js/helpdeskview.js, searchmembers.php
=> Return corrected result of search field

js/helpdeskview.js, members.php, searchmembers.php
=> Added the handler for removed and add searchfields

locallib.php, members.php
=> Added methods to manage the members category and display data on the page

js/helpdeskview.js, locallib.php, members.php
=> added function to get members by category id, and delete members by categoryid and and display it on each columns

addcategory.php, categories/managecategories.php, categories/viewcontroller.php, delete.php, js/helpdeskview.js, members.php, searchmembers.php
=> added data for edit the category info and added able to find users for chosen category

addcategory.php, categories/viewcontroller.php, renderer.php, views/viewassignedtickets.php
=> Added able to create and edit category
